# Generated by Django 5.2.10 on 2026-01-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_add_slack_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attackincident',
            new_name='incidents_a_source__d4f19a_idx',
            old_name='incidents_sourc_f0e5d9_idx',
        ),
        migrations.AlterField(
            model_name='attackincident',
            name='attack_type',
            field=models.CharField(choices=[('ddos', 'ddos'), ('port_scan', 'port_scan'), ('bruteforce', 'bruteforce'), ('api_enum', 'api_enum')], db_index=True, max_length=50),
        ),
    ]
